### ISSUE TITLE
Don't panic on file read/open/parse errors

### ISSUE THREAD

**Issue by sunshowers** [TedDriggs/syn-inline-mod#11]
Looks like this code currently panics if there's an error while the file's being opened, read or parsed: https://github.com/TedDriggs/syn-inline-mod/blob/master/src/resolver.rs#L22-L27

As a library, `syn-inline-mod` should probably return errors for consumers to process as they wish instead.

**Comment by TedDriggs** [comment]
Those panics are guarded [here](https://github.com/TedDriggs/syn-inline-mod/blob/master/src/visitor.rs#L74), so you shouldn't be encountering them in the wild. Are you seeing panics/can you share the calling code?

**Comment by sunshowers** [comment]
That only checks for if the file is absent, not if the file could not be read (due to an io error) or the file is invalid Rust source code.

I've overhauled the error handling locally to handle all such situations and will submit a PR shortly.

**Comment by TedDriggs** [comment]
This is now live in v0.4.0 of the crate.
