### ISSUE TITLE
update synt, proc-macro2 & quote dependencies

### ISSUE THREAD

**Issue by ctaggart** [TedDriggs/syn-inline-mod#8]
rust-reduce took a dependency on this crate and I'm running into an error running it https://github.com/jethrogb/rust-reduce/issues/5. I think upgrading the dependencies would help.

https://github.com/TedDriggs/syn-inline-mod/blob/3704707074368a8b59d194c3ea705e73d558cdaf/Cargo.toml#L12-L17

The latest are:
https://github.com/dtolnay/syn 1.0.4
https://github.com/alexcrichton/proc-macro2 1.0.6
https://github.com/dtolnay/quote 1.0.2

**Comment by TedDriggs** [comment]
If you're able to put up a PR I'll happily review it. I'm a little time-constrained right now, so I may not be able to do it myself for a while.

**Comment by chuck-flowers** [comment]
I upgraded the dependencies in PR #9. I'm hoping it fixes this issue and #7 as well. Once it gets accepted both issues should be retested.

**Comment by TedDriggs** [comment]
I've published v0.3.0 with PR #9 included.
